---
- hosts:  uat-servers
  tasks:
  - name: Directory in container
    file:
      path: /var/tmp/flask_{{BUILD_NUMBER}}
      state: directory 
  - name: move zip
    copy:
      src: /var/lib/jenkins/workspace/flask-compose/flaskapp.zip
      dest: /var/tmp/flask_{{BUILD_NUMBER}}
      
  - name: uncompress
    shell: cd /var/tmp/flask_{{BUILD_NUMBER}};unzip flaskapp.zip

  - name: docker compose
    shell: cd /var/tmp/flask_{{BUILD_NUMBER}}; docker compose up -d
      